CREATE TABLE [dbo].[CollectionRequiredFields]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[CollectionId] INT NOT NULL,
	[Boolean1FieldRequired] BIT NOT NULL,
	[Boolean1FieldName] NVARCHAR(100) NOT NULL,
	[Boolean2FieldRequired] BIT NOT NULL,
	[Boolean2FieldName] NVARCHAR(100) NOT NULL,
	[Boolean3FieldRequired] BIT NOT NULL,
	[Boolean3FieldName] NVARCHAR(100) NOT NULL,
	[Date1FieldRequired] BIT NOT NULL,
	[Date1FieldName] NVARCHAR(100) NOT NULL,
	[Date2FieldRequired] BIT NOT NULL,
	[Date2FieldName] NVARCHAR(100) NOT NULL,
	[Date3FieldRequired] BIT NOT NULL,
	[Date3FieldName] NVARCHAR(100) NOT NULL,
	[Int1FieldRequired] BIT NOT NULL,
	[Int1FieldName] NVARCHAR(100) NOT NULL,
	[Int2FieldRequired] BIT NOT NULL,
	[Int2FieldName] NVARCHAR(100) NOT NULL,
	[Int3FieldRequired] BIT NOT NULL,
	[Int3FieldName] NVARCHAR(100) NOT NULL,
	[String1FieldRequired] BIT NOT NULL,
	[String1FieldName] NVARCHAR(100) NOT NULL,
	[String2FieldRequired] BIT NOT NULL,
	[String2FieldName] NVARCHAR(100) NOT NULL,
	[String3FieldRequired] BIT NOT NULL,
	[String3FieldName] NVARCHAR(100) NOT NULL,
	[Text1FieldRequired] BIT NOT NULL,
	[Text1FieldName] NVARCHAR(100) NOT NULL,
	[Text2FieldRequired] BIT NOT NULL,
	[Text2FieldName] NVARCHAR(100) NOT NULL,
	[Text3FieldRequired] BIT NOT NULL,
	[Text3FieldName] NVARCHAR(100) NOT NULL,
	CONSTRAINT pk_CollectionRequiredFields PRIMARY KEY([Id])
)
